# Generated by Django 2.0.6 on 2019-08-26 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_name', models.CharField(max_length=100)),
                ('movie_category', models.CharField(max_length=50)),
                ('movie_img', models.ImageField(upload_to='')),
                ('movie_ticket_number', models.IntegerField()),
                ('movie_ticket_price', models.FloatField()),
                ('movie_venue', models.CharField(max_length=150)),
                ('movie_show_date', models.DateTimeField()),
                ('movie_description', models.TextField()),
            ],
        ),
    ]
