# Generated by Django 2.0.6 on 2019-08-26 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='movie_img',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
