# Generated by Django 2.0.6 on 2019-08-26 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_auto_20190826_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='movie_img',
            field=models.ImageField(upload_to='movies/static/images/'),
        ),
    ]
