# Generated by Django 2.0.6 on 2019-08-28 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_auto_20190826_1625'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='movie_ticket_booked',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
