# Generated by Django 2.0.6 on 2019-08-29 04:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_movie_movie_ticket_booked'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendant_name', models.CharField(max_length=35)),
                ('attendant_booked_sit', models.IntegerField(blank=True)),
                ('attendant_booked_movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.Movie')),
            ],
        ),
    ]
